# Configuration file for the Binary_Network
---

data_load: csv

num_columns: 12

train_new: False

Binary_Network:
  initialisations:
    hidden_dim: 7
    output_dim: 1
    batch_size: 1
    model_save_path: trained_model.pth

